<!doctype html>
<html lang="ja">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
  <title>ふたりのNG</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@400;500;700&display=swap');
    :root { --ink:#f8f0ff; --soft:#c6b6d8; --paper:#171329; --pink:#ee91c9; --pink-dark:#d859a4; --lav:#3b2e67; --yellow:#ffdc83; --mint:#87dfd2; --line:#42365f; }
    *{box-sizing:border-box} body{margin:0;background:#090619;color:var(--ink);font-family:'Zen Maru Gothic',system-ui,sans-serif;font-size:15px;min-height:100vh} button,input,textarea{font:inherit} button{border:0;cursor:pointer;color:inherit}
    .app{max-width:480px;min-height:100vh;margin:auto;background:radial-gradient(circle at 18% 10%,#483871 0,transparent 25%),radial-gradient(circle at 90% 42%,#173e62 0,transparent 27%),var(--paper);position:relative;overflow:hidden}.app:before{content:'✦  ·  ✧     ·  ✦       ⋆      ✧   ·  ✦      ·   ⋆';position:absolute;inset:14px 0 auto;font-size:14px;letter-spacing:9px;color:#fff8c5b0;pointer-events:none}.screen{display:none;min-height:100vh;padding:28px 20px 34px;animation:in .35s ease;position:relative;z-index:1}.screen.active{display:flex;flex-direction:column}@keyframes in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
    .brand{font-size:15px;font-weight:700;letter-spacing:.08em;color:#ffcaed;display:flex;align-items:center;gap:6px}.brand b{font-size:22px}.hero{padding-top:40px}.hero-art{height:275px;position:relative;margin:16px 0 24px}.cloud{position:absolute;border-radius:50%;filter:blur(.2px)}.cloud.one{width:220px;height:220px;background:radial-gradient(circle at 30% 30%,#8779db,#493985);left:22px;top:19px}.cloud.two{width:170px;height:170px;background:radial-gradient(circle at 40% 35%,#84e3da,#285580);right:-34px;bottom:5px}.chat-bubble{position:absolute;border-radius:24px;padding:14px 18px;font-weight:700;box-shadow:0 9px 20px #00000044}.chat-bubble.a{top:62px;left:0;background:#292040;transform:rotate(-6deg)}.chat-bubble.b{top:136px;right:0;background:#9a4a9b;transform:rotate(5deg)}.heart{position:absolute;font-size:48px;top:105px;left:45%;filter:drop-shadow(0 4px 8px #b86cff)}
    .home-planet{width:236px;height:236px;border-radius:50%;margin:auto;background:radial-gradient(circle at 32% 28%,#b6c6ff 0 4%,transparent 5%),radial-gradient(circle at 68% 66%,#5ccddd 0 6%,transparent 7%),radial-gradient(circle at 40% 40%,#8b7be8 0,#4d3c93 58%,#24194f 100%);box-shadow:inset -24px -22px 35px #100b3388,0 0 45px #aa8ff070;position:relative}.home-planet:after{content:'';position:absolute;width:315px;height:54px;border:10px solid #ffb6dfcc;border-radius:50%;left:-41px;top:94px;transform:rotate(-17deg);box-shadow:0 0 18px #f6a5d788}
    h1{font-size:31px;line-height:1.38;margin:0 0 12px;letter-spacing:-.04em}h2{font-size:24px;line-height:1.45;margin:14px 0 7px;letter-spacing:-.03em}p{line-height:1.75;color:var(--soft);margin:0}.bottom-actions{margin-top:auto;padding-top:24px}.primary,.secondary{width:100%;padding:16px 18px;border-radius:18px;font-weight:700;font-size:16px}.primary{background:var(--pink-dark);color:#fff;box-shadow:0 7px 0 #a93d81;transition:.15s}.primary:active{box-shadow:0 2px 0 #a93d81;transform:translateY(5px)}.secondary{background:#ffffff12;color:var(--ink);border:1px solid var(--line);margin-top:16px}.tiny-note{text-align:center;font-size:12px;margin-top:20px}
    .topbar{display:flex;align-items:center;justify-content:space-between}.back{background:transparent;font-weight:700;padding:8px 0;font-size:14px}.back::before{content:'‹';font-size:28px;vertical-align:-3px;margin-right:4px}.step{font-size:12px;color:#f8d8ee;background:#44265d;padding:7px 10px;border-radius:999px}.room-card{background:linear-gradient(145deg,#3b2d75,#154c6b);border-radius:28px;padding:24px;margin:32px 0 16px;text-align:center}.room-card .emoji{font-size:54px}.room-code{font-size:35px;letter-spacing:.13em;font-weight:700;margin:15px 0 8px}.copy{background:#ffffff1f;color:var(--ink);border-radius:12px;padding:10px 14px;font-size:13px;font-weight:700}.card{background:#ffffff10;border:1px solid var(--line);border-radius:22px;padding:18px;margin:16px 0}.input-label{font-weight:700;font-size:14px;margin:18px 0 8px;display:block}input,textarea{width:100%;background:#100d22;border:1.5px solid #574772;border-radius:15px;padding:15px;color:var(--ink);outline:none}input:focus,textarea:focus{border-color:var(--pink-dark);box-shadow:0 0 0 3px #fbbcc450}textarea{min-height:92px;resize:none}.hint{font-size:12px;margin-top:7px}.theme-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:19px}.theme{padding:14px;border-radius:16px;background:#ffffff0d;border:1.5px solid var(--line);text-align:left;font-weight:700}.theme.selected{border-color:#f6a5d7;background:#a64e9a55}.theme span{display:block;font-size:20px;margin-bottom:4px}.safety{display:none}
    .time-options{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:9px}.time-option{padding:12px 4px;background:#ffffff0d;color:var(--ink);border:1px solid var(--line);border-radius:14px;font-weight:700}.time-option.selected{background:#a64e9a55;border-color:#f6a5d7}
    .waiting{align-items:center;text-align:center;padding-top:90px}.pulse{width:120px;height:120px;border-radius:50%;background:var(--mint);display:grid;place-items:center;font-size:45px;margin:34px auto;position:relative}.pulse:after{content:'';position:absolute;inset:-10px;border:2px solid #b6dfcb;border-radius:50%;animation:pulse 1.7s infinite}@keyframes pulse{to{transform:scale(1.22);opacity:0}}.join-status{font-size:14px;margin-top:8px}.join-status b{color:#399d6f}
    .game{padding:18px 16px 16px;background:transparent}.game-head{display:flex;justify-content:space-between;align-items:center}.timer{font-size:22px;font-weight:700;font-variant-numeric:tabular-nums}.add-minute{background:#ffffff12;border:1px solid var(--line);color:#bff8f0;border-radius:999px;padding:7px 9px;font-size:12px;font-weight:700}.score{font-size:12px;padding:7px 10px;border-radius:999px;background:var(--yellow);color:#4e3c42;font-weight:700}.game-context{background:#3d2b69;border-radius:18px;padding:13px 15px;margin:18px 0 12px;font-size:13px;display:flex;justify-content:space-between;gap:9px}.game-context strong{color:#ffbfdf}.messages{flex:1;min-height:250px;padding:12px 2px}.msg{max-width:78%;padding:12px 14px;border-radius:18px;margin:10px 0;line-height:1.55;font-size:14px}.msg.them{background:#302746;border-bottom-left-radius:5px}.msg.me{background:#914d91;margin-left:auto;border-bottom-right-radius:5px}.event{margin:10px 0;background:#534279;padding:12px 14px;border-radius:14px;font-size:13px;font-weight:700;text-align:center}.chat-compose{display:flex;gap:9px;align-items:center;border-top:1px solid var(--line);padding-top:12px}.chat-compose input{padding:13px;min-width:0}.send{background:var(--pink-dark);color:#fff;border-radius:14px;width:48px;height:48px;font-size:20px}.helper-row{display:flex;gap:8px;margin-top:11px}.helper{background:#ffffff10;color:var(--ink);border:1px solid var(--line);border-radius:999px;padding:9px 12px;font-size:12px;font-weight:700}.mic{margin-left:auto}.overlay{display:none;position:absolute;inset:0;background:#090616ba;z-index:5;padding:28px 20px;align-items:center;justify-content:center}.overlay.show{display:flex}.modal{background:var(--paper);border-radius:28px;padding:28px 22px;text-align:center;width:100%;box-shadow:0 20px 50px #000}.modal .burst{font-size:55px}.modal h2{margin:8px 0}.modal .primary{margin-top:22px}
    .result{padding-top:36px;text-align:center}.confetti{font-size:46px;letter-spacing:8px;margin:10px 0}.result-score{background:linear-gradient(145deg,#225c70,#314c88);border-radius:26px;margin:28px 0 18px;padding:22px}.result-score strong{display:block;font-size:38px;color:#b9fff4;margin:4px}.reveal-card{text-align:left;background:#ffffff10;border:1px solid var(--line);border-radius:23px;padding:19px;margin-top:14px}.reveal-card small{color:var(--soft);font-weight:700}.answer{font-size:22px;font-weight:700;margin:7px 0}.match{color:#a0f6d5;font-weight:700;font-size:13px}.understanding{display:flex;align-items:center;gap:13px;text-align:left;background:#493566;border-radius:19px;padding:14px;margin-top:15px}.ring{width:54px;height:54px;border-radius:50%;display:grid;place-items:center;background:conic-gradient(var(--pink-dark) 0 82%, #211a36 82%);position:relative;font-size:12px;font-weight:700}.ring:before{content:'';width:42px;height:42px;background:#211a36;border-radius:50%;position:absolute}.ring span{position:relative}.why{background:var(--lav);border-radius:22px;padding:18px;text-align:left;margin:20px 0}.why h3{margin:0 0 8px;font-size:16px}.why p{font-size:13px}.quick-question{background:#ffffff14;border-radius:14px;padding:12px;margin-top:10px;font-size:13px;font-weight:700}.nav{display:flex;justify-content:space-around;border-top:1px solid var(--line);padding:11px 0 0;margin-top:auto;color:var(--soft);font-size:11px}.nav button{background:transparent;font-size:11px}.nav button span{font-size:19px;display:block;margin-bottom:2px}.empty{height:10px}
    @media(min-width:520px){body{padding:20px}.app{min-height:calc(100vh - 40px);border-radius:30px;box-shadow:0 18px 55px #66475820}}
  </style>
</head>
<body><main class="app">
  <section class="screen active" id="home"><div class="hero" style="display:flex;flex:1;align-items:center"><div class="home-planet" aria-label="惑星"></div></div><div class="bottom-actions"><button class="primary" onclick="show('create')">ルームをつくる</button><button class="secondary" onclick="show('join')">ルームに参加する</button></div></section>
  <section class="screen" id="create"><div class="topbar"><button class="back" onclick="show('home')">戻る</button><span class="step">1 / 4</span></div><h2>今夜のテーマを<br>選ぼう</h2><p>テーマがあると、会話のはじまりがもっと自然に。</p><div class="theme-grid" id="themes"><button class="theme selected" data-theme="食べ物">🍜 食べ物</button><button class="theme" data-theme="趣味">🎨 趣味</button><button class="theme" data-theme="旅行">✈️ 旅行</button><button class="theme" data-theme="子どもの頃">🧸 子どもの頃</button><button class="theme" data-theme="好きなもの">💛 好きなもの</button><button class="theme" data-theme="完全ランダム">🎲 ランダム</button></div><div class="bottom-actions"><button class="primary" onclick="makeRoom()">ルームをつくる</button></div></section>
  <section class="screen" id="room"><div class="topbar"><button class="back" onclick="show('create')">戻る</button><span class="step">招待中</span></div><h2>星間ルームを招待</h2><div class="room-card"><div class="emoji">🛸</div><div class="room-code" id="roomCode">NICO-82</div><button class="copy" onclick="copyCode()">コードをコピー</button></div><div class="card"><b>相手を待っています…</b></div><div class="bottom-actions"><button class="secondary" onclick="show('waiting')">参加をシミュレーション</button></div></section>
  <section class="screen" id="join"><div class="topbar"><button class="back" onclick="show('home')">戻る</button><span class="step">参加</span></div><h2>ルームに参加する</h2><p>相手から届いた6桁のルームコードを入力してね。</p><label class="input-label" for="joinCode">ルームコード</label><input id="joinCode" placeholder="例：NICO-82" autocapitalize="characters" /><div class="bottom-actions"><button class="primary" onclick="show('waiting')">ルームに入る</button></div></section>
  <section class="screen waiting" id="waiting"><div class="brand"><b>✦</b> ふたりのNG</div><div class="pulse">🛸</div><h2>ふたりそろった！</h2><p class="join-status"><b>相手</b> が参加しました</p><div class="bottom-actions"><button class="primary" onclick="show('set')">NGワードを決める</button></div></section>
  <section class="screen" id="set"><div class="topbar"><button class="back" onclick="show('home')">戻る</button><span class="step">2 / 4</span></div><h2>相手に言わせたい<br>NGワードは？</h2><label class="input-label" for="ngWord">あなたのNGワード</label><input id="ngWord" maxlength="20" placeholder="例：ラーメン" /><div class="bottom-actions"><button class="primary" onclick="setWord()">これにする</button></div></section>
  <section class="screen" id="guess"><div class="topbar"><button class="back" onclick="show('set')">戻る</button><span class="step">3 / 4</span></div><div style="font-size:48px;margin-top:30px">🪐</div><h2>相手なら、<br>何を選びそう？</h2><label class="input-label" for="guessWord">相手のNGワード予想</label><input id="guessWord" maxlength="20" placeholder="例：カレー" /><label class="input-label">プレイ時間</label><div class="time-options" id="timeOptions"><button class="time-option" data-seconds="30">30秒</button><button class="time-option" data-seconds="60">1分</button><button class="time-option selected" data-seconds="120">2分</button><button class="time-option" data-seconds="180">3分</button></div><div class="bottom-actions"><button class="primary" onclick="startGame()">会話をはじめる</button></div></section>
  <section class="screen game" id="game"><div class="game-head"><button class="back" onclick="endGame()">終わる</button><div class="timer" id="timer">02:00</div><button class="add-minute" onclick="addMinute()">＋1分</button><span class="score">あなた 0pt</span></div><div class="game-context"><span>テーマ：<strong id="gameTheme">食べ物</strong></span><span>予想：<strong id="gameGuess">カレー</strong></span></div><div class="messages" id="messages"><div class="msg them">今日は何食べた？🍽️</div><div class="msg me">まだ迷ってる！そっちは？</div><div class="event">⚡ 10秒質問：今いちばん食べたいものは？</div></div><div class="chat-compose"><input id="chatInput" placeholder="メッセージを入力" onkeydown="if(event.key==='Enter')sendMessage()" /><button class="send" onclick="sendMessage()" aria-label="送信">➤</button></div><div class="helper-row"><button class="helper" onclick="questionCard()">🃏 質問カード</button><button class="helper mic" onclick="voiceHint()">🎙️ 音声で話す</button></div><div class="overlay" id="ngOverlay"><div class="modal"><div class="burst">💥</div><h2>NGワード！</h2><p>「<b id="saidWord">ラーメン</b>」<br><b>+100pt</b></p><button class="primary" onclick="endGame()">結果を見る</button></div></div></section>
  <section class="screen result" id="result"><div class="brand"><b>✦</b> ふたりのNG</div><div class="confetti">🌟 🪐 ✨</div><h1>いい会話だったね！</h1><div class="result-score"><span>会話ポイント</span><strong>+150</strong></div><div class="reveal-card"><small>あなたの予想</small><div class="answer" id="resultGuess">カレー</div><small>相手のNGワード</small><div class="answer">ラーメン</div><div class="match" id="matchText">惜しい！</div></div><div class="understanding"><div class="ring"><span>82%</span></div><div><b>相手理解度 +2%</b></div></div><div class="why"><h3>「なんでラーメンにしたの？」</h3><div class="quick-question">🍜 最近いちばんおいしかったラーメンは？</div></div><div class="bottom-actions"><button class="primary" onclick="show('collection')">会話をつづける</button><button class="secondary" onclick="show('create')">もう一回あそぶ</button></div></section>
  <section class="screen" id="collection"><div class="topbar"><button class="back" onclick="show('result')">戻る</button><span class="step">ふたりの記録</span></div><div style="font-size:46px;margin-top:18px">🌌</div><h2>ふたりの共通点</h2><div class="card" style="background:#493566"><b>✨ 新しい共通点を発見！</b></div><div class="card"><div style="font-size:22px">🍜　ラーメンが好き</div><hr style="border:0;border-top:1px solid var(--line);margin:14px 0"><div style="font-size:22px">🎬　映画が好き</div><hr style="border:0;border-top:1px solid var(--line);margin:14px 0"><div style="font-size:22px">🌊　海に行きたい</div></div><div class="why"><h3>次の質問カード</h3><div class="quick-question">「子どもの頃、よく食べたものは？」</div></div><div class="bottom-actions"><button class="primary" onclick="show('create')">次のラウンドへ</button></div><nav class="nav"><button onclick="show('home')"><span>⌂</span>ホーム</button><button onclick="show('collection')"><span>✦</span>ふたり</button><button onclick="show('create')"><span>＋</span>あそぶ</button><button onclick="alert('プロフィール')"><span>☺</span>プロフィール</button></nav></section>
</main><script>
  const state={theme:'食べ物',ng:'',guess:'カレー',seconds:120,duration:120,timer:null};
  function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)}
  document.querySelectorAll('.theme').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.theme').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');state.theme=button.dataset.theme;}));
  document.querySelectorAll('.time-option').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.time-option').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');state.duration=Number(button.dataset.seconds);}));
  function makeRoom(){document.getElementById('roomCode').textContent='NICO-'+Math.floor(10+Math.random()*90);show('room')}
  async function copyCode(){try{await navigator.clipboard.writeText(document.getElementById('roomCode').textContent);alert('ルームコードをコピーしました');}catch{alert('ルームコード：'+document.getElementById('roomCode').textContent)}}
  function setWord(){const value=document.getElementById('ngWord').value.trim();const blocked=['ばか','死ね','きもい','殺'];if(!value)return alert('NGワードを入力してね');if(blocked.some(word=>value.includes(word)))return alert('その言葉は使えません。別の言葉にしてね。');state.ng=value;show('guess')}
  function startGame(){state.guess=document.getElementById('guessWord').value.trim()||'カレー';document.getElementById('gameTheme').textContent=state.theme;document.getElementById('gameGuess').textContent=state.guess;state.seconds=state.duration;document.getElementById('timer').textContent=String(Math.floor(state.seconds/60)).padStart(2,'0')+':'+String(state.seconds%60).padStart(2,'0');clearInterval(state.timer);state.timer=setInterval(tick,1000);show('game')}
  function tick(){state.seconds--;const m=String(Math.max(0,Math.floor(state.seconds/60))).padStart(2,'0'),s=String(Math.max(0,state.seconds%60)).padStart(2,'0');document.getElementById('timer').textContent=m+':'+s;if(state.seconds<=0)endGame()}
  function addMinute(){state.seconds+=60;document.getElementById('timer').textContent=String(Math.floor(state.seconds/60)).padStart(2,'0')+':'+String(state.seconds%60).padStart(2,'0')}
  function sendMessage(){const input=document.getElementById('chatInput'),message=input.value.trim();if(!message)return;const messageEl=document.createElement('div');messageEl.className='msg me';messageEl.textContent=message;document.getElementById('messages').append(messageEl);input.value='';document.getElementById('messages').scrollTop=9999;if(message.includes('ラーメン')){document.getElementById('saidWord').textContent='ラーメン';document.getElementById('ngOverlay').classList.add('show')}else setTimeout(()=>{const reply=document.createElement('div');reply.className='msg them';reply.textContent='それいいね！もっと聞かせて 😊';document.getElementById('messages').append(reply)},650)}
  function questionCard(){const cards=['最近ちょっと嬉しかったことは？','子どもの頃、好きだった食べ物は？','今いちばん行きたい場所は？'];const card=cards[Math.floor(Math.random()*cards.length)];const el=document.createElement('div');el.className='event';el.textContent='🃏 質問カード：'+card;document.getElementById('messages').append(el)}
  function voiceHint(){alert('音声通話は連携機能として追加予定です。今は気持ちを声に出しながら、メッセージでも楽しめます。')}
  function endGame(){clearInterval(state.timer);document.getElementById('ngOverlay').classList.remove('show');document.getElementById('resultGuess').textContent=state.guess;document.getElementById('matchText').textContent=state.guess==='ラーメン'?'予想的中！ +100理解度ポイント':'惜しい！でも食べ物の好み、近いかも。';show('result')}
</script></body></html>
